/*============================================================================*\
 * This file was generated by the SCG framework.
 *
 * The configuration parameters were checked statically for correctness
 * by DETECT tool and code generator. DO NOT EDIT THIS FILE MANUALLY!!!
 *
 * \b Application:        ADC \n
 * \b Target:             NEC 78K0R \n
 * \b Compiler:           see Adc.h \n
 * \b Module:             Adc_Cfg.c \n
 * \b File-Revision:      1.1.1 \n
 * \b Changeable-by-user: No \n
 * \b Module-Owner:       SSA Team \n
 * \b Last-Modified:      2010/11/26 16:54:33\n
 * \b Classification:     CONFIDENTIAL \n
\*============================================================================*/

/**\file
 *
 * \brief Configuration File for SSA ADC module.
 *
 * \details This file contains the definitions of configurable objects
 *  of the ADC module for SSA. \n
 *  If API services are implemented as macros this file can be empty.
 */

/*============================================================================*\
 * File generated on 2010/11/26 16:54:33
 * Generated using code generator (EPD) v1.1.1
 *
\*============================================================================*/

/*============================================================================*\
 *
 * Copyright 2010  Controls & Security, All Rights Reserved
 * It is not allowed to reproduce or utilize parts of this document in any form
 * or by any means, including photocopying and microfilm, without permission in
 * written by  Electronics & Safety Division.
 *
\*============================================================================*/

/*============================================================================*\
 * PREPROCESSOR DIRECTIVES
\*============================================================================*/

/* INCLUDE DIRECTIVES FOR STANDARD HEADERS -----------------------------------*/

#include "Adc.h"


/*
 * Version controls for Adc.h file.
 */
#define EXPECTED_ADC_CFG_AR_MAJOR_VERSION                    (2u)
#define EXPECTED_ADC_CFG_AR_MINOR_VERSION                    (1u)
#define EXPECTED_ADC_CFG_AR_PATCH_VERSION                    (0u)

#define EXPECTED_ADC_CFG_H_MAJOR_VERSION                    (1u)
#define EXPECTED_ADC_CFG_H_MINOR_VERSION                    (1u)

#if( (ADC_AR_MAJOR_VERSION != EXPECTED_ADC_CFG_AR_MAJOR_VERSION) || \
     (ADC_AR_MINOR_VERSION != EXPECTED_ADC_CFG_AR_MINOR_VERSION) || \
     (ADC_AR_PATCH_VERSION != EXPECTED_ADC_CFG_AR_PATCH_VERSION) )
#error "AUTOSAR version mismatch between Adc_Cfg.c and Adc.h files."
#endif

#if( (ADC_SW_MAJOR_VERSION != EXPECTED_ADC_CFG_H_MAJOR_VERSION) || \
     (ADC_SW_MINOR_VERSION != EXPECTED_ADC_CFG_H_MINOR_VERSION) )
#error "The version of the Adc_Cfg.c file does not match the version of the Adc.h file"
#endif

/* INCLUDE DIRECTIVES FOR OTHER HEADERS --------------------------------------*/

/* LOCAL DEFINES OR CONSTANTS --------------------------------------------*/

/* INCLUDE DIRECTIVES FOR OTHER HEADERS --------------------------------------*/

/* LOCAL DEFINES FOR CONSTANTS -----------------------------------------------*/

/* LOCAL DEFINE MACROS (#, ##) -----------------------------------------------*/

//1 channel 0:
#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT0 { \
   ADC_GROUP0_START_CHANNEL,                 \
   ADC_GROUP0_LENGTH,                        \
   ADC_GROUP0_PRIORITY,                      \
   ADC_GROUP0_NOTIFI_FUNCTION,               \
   ADC_GROUP0_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT0 { \
   ADC_GROUP0_START_CHANNEL,                 \
   ADC_GROUP0_LENGTH,                        \
   ADC_GROUP0_PRIORITY,                      \
   ADC_GROUP0_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER0 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP0_result[(ADC_GROUP0_LENGTH)]

//1 channel 1:
#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT1 { \
   ADC_GROUP1_START_CHANNEL,                 \
   ADC_GROUP1_LENGTH,                        \
   ADC_GROUP1_PRIORITY,                      \
   ADC_GROUP1_NOTIFI_FUNCTION,               \
   ADC_GROUP1_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT1 { \
   ADC_GROUP1_START_CHANNEL,                 \
   ADC_GROUP1_LENGTH,                        \
   ADC_GROUP1_PRIORITY,                      \
   ADC_GROUP1_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER1 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP1_result[(ADC_GROUP1_LENGTH)]

//1 channel2:
#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT2 { \
   ADC_GROUP2_START_CHANNEL,                 \
   ADC_GROUP2_LENGTH,                        \
   ADC_GROUP2_PRIORITY,                      \
   ADC_GROUP2_NOTIFI_FUNCTION,               \
   ADC_GROUP2_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT2 { \
   ADC_GROUP2_START_CHANNEL,                 \
   ADC_GROUP2_LENGTH,                        \
   ADC_GROUP2_PRIORITY,                      \
   ADC_GROUP2_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/

/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER2 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP2_result[(ADC_GROUP2_LENGTH)]
  


#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT3 { \
   ADC_GROUP3_START_CHANNEL,                 \
   ADC_GROUP3_LENGTH,                        \
   ADC_GROUP3_PRIORITY,                      \
   ADC_GROUP3_NOTIFI_FUNCTION,               \
   ADC_GROUP3_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT3 { \
   ADC_GROUP3_START_CHANNEL,                 \
   ADC_GROUP3_LENGTH,                        \
   ADC_GROUP3_PRIORITY,                      \
   ADC_GROUP3_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER3 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP3_result[(ADC_GROUP3_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT4 { \
   ADC_GROUP4_START_CHANNEL,                 \
   ADC_GROUP4_LENGTH,                        \
   ADC_GROUP4_PRIORITY,                      \
   ADC_GROUP4_NOTIFI_FUNCTION,               \
   ADC_GROUP4_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT4 { \
   ADC_GROUP4_START_CHANNEL,                 \
   ADC_GROUP4_LENGTH,                        \
   ADC_GROUP4_PRIORITY,                      \
   ADC_GROUP4_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER4 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP4_result[(ADC_GROUP4_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT5 { \
   ADC_GROUP5_START_CHANNEL,                 \
   ADC_GROUP5_LENGTH,                        \
   ADC_GROUP5_PRIORITY,                      \
   ADC_GROUP5_NOTIFI_FUNCTION,               \
   ADC_GROUP5_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT5 { \
   ADC_GROUP5_START_CHANNEL,                 \
   ADC_GROUP5_LENGTH,                        \
   ADC_GROUP5_PRIORITY,                      \
   ADC_GROUP5_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER5 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP5_result[(ADC_GROUP5_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT6 { \
   ADC_GROUP6_START_CHANNEL,                 \
   ADC_GROUP6_LENGTH,                        \
   ADC_GROUP6_PRIORITY,                      \
   ADC_GROUP6_NOTIFI_FUNCTION,               \
   ADC_GROUP6_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT6 { \
   ADC_GROUP6_START_CHANNEL,                 \
   ADC_GROUP6_LENGTH,                        \
   ADC_GROUP6_PRIORITY,                      \
   ADC_GROUP6_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/

#if 0
/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER6 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP6_result[(ADC_GROUP6_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT7 { \
   ADC_GROUP7_START_CHANNEL,                 \
   ADC_GROUP7_LENGTH,                        \
   ADC_GROUP7_PRIORITY,                      \
   ADC_GROUP7_NOTIFI_FUNCTION,               \
   ADC_GROUP7_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT7 { \
   ADC_GROUP7_START_CHANNEL,                 \
   ADC_GROUP7_LENGTH,                        \
   ADC_GROUP7_PRIORITY,                      \
   ADC_GROUP7_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER7 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP7_result[(ADC_GROUP7_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT8 { \
   ADC_GROUP8_START_CHANNEL,                 \
   ADC_GROUP8_LENGTH,                        \
   ADC_GROUP8_PRIORITY,                      \
   ADC_GROUP8_NOTIFI_FUNCTION,               \
   ADC_GROUP8_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT8 { \
   ADC_GROUP8_START_CHANNEL,                 \
   ADC_GROUP8_LENGTH,                        \
   ADC_GROUP8_PRIORITY,                      \
   ADC_GROUP8_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER8 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP8_result[(ADC_GROUP8_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT9 { \
   ADC_GROUP9_START_CHANNEL,                 \
   ADC_GROUP9_LENGTH,                        \
   ADC_GROUP9_PRIORITY,                      \
   ADC_GROUP9_NOTIFI_FUNCTION,               \
   ADC_GROUP9_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT9 { \
   ADC_GROUP9_START_CHANNEL,                 \
   ADC_GROUP9_LENGTH,                        \
   ADC_GROUP9_PRIORITY,                      \
   ADC_GROUP9_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER9 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP9_result[(ADC_GROUP9_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT10 { \
   ADC_GROUP10_START_CHANNEL,                 \
   ADC_GROUP10_LENGTH,                        \
   ADC_GROUP10_PRIORITY,                      \
   ADC_GROUP10_NOTIFI_FUNCTION,               \
   ADC_GROUP10_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT10 { \
   ADC_GROUP10_START_CHANNEL,                 \
   ADC_GROUP10_LENGTH,                        \
   ADC_GROUP10_PRIORITY,                      \
   ADC_GROUP10_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER10 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP10_result[(ADC_GROUP10_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT11 { \
   ADC_GROUP11_START_CHANNEL,                 \
   ADC_GROUP11_LENGTH,                        \
   ADC_GROUP11_PRIORITY,                      \
   ADC_GROUP11_NOTIFI_FUNCTION,               \
   ADC_GROUP11_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT11 { \
   ADC_GROUP11_START_CHANNEL,                 \
   ADC_GROUP11_LENGTH,                        \
   ADC_GROUP11_PRIORITY,                      \
   ADC_GROUP11_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER11 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP11_result[(ADC_GROUP11_LENGTH)]

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT12 { \
   ADC_GROUP12_START_CHANNEL,                 \
   ADC_GROUP12_LENGTH,                        \
   ADC_GROUP12_PRIORITY,                      \
   ADC_GROUP12_NOTIFI_FUNCTION,               \
   ADC_GROUP12_result                         \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_LIST_STD_INIT12 { \
   ADC_GROUP12_START_CHANNEL,                 \
   ADC_GROUP12_LENGTH,                        \
   ADC_GROUP12_PRIORITY,                      \
   ADC_GROUP12_result                         \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/** Macro for defining results buffer for specific group. */
#define ADC_DEFINE_GROUP_RESULT_BUFFER12 \
  _STATIC_ VAR(Adc_ValueGroupType,ADC_VAR) ADC_GROUP12_result[(ADC_GROUP12_LENGTH)]
#endif

#if (STD_ON == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_DUMMY { \
   0,                                        \
   0,                                        \
   0,                                        \
   NULL_PTR,                                 \
   NULL_PTR                                  \
}
#endif /*(STD_ON == ADC_GRP_NOTIF_CAPABILITY)*/

#if (STD_OFF == ADC_GRP_NOTIF_CAPABILITY)
#define ADC_GROUP_DUMMY { \
   0,                                        \
   0,                                        \
   0,                                        \
   NULL_PTR                                  \
}
#endif /*(STD_OFF == ADC_GRP_NOTIF_CAPABILITY)*/


/*============================================================================*\
 * LOCAL TYPEDEF DECLARATIONS
\*============================================================================*/

/* ENUMS ---------------------------------------------------------------------*/

/* STRUCTS -------------------------------------------------------------------*/

/* UNIONS --------------------------------------------------------------------*/

/* OTHER TYPEDEFS ------------------------------------------------------------*/

/*============================================================================*\
 * OBJECT DEFINITIONS
\*============================================================================*/

/* EXPORTED OBJECTS ----------------------------------------------------------*/

/* Groups' results buffer. Configuration relay on
 * Count of defines should be the same as a group count.
 */
ADC_DEFINE_GROUP_RESULT_BUFFER0; //ADC_GROUP0_result ---AMP.AMP_DIAG
ADC_DEFINE_GROUP_RESULT_BUFFER1; //ADC_GROUP0_result ---VOLT_DET
ADC_DEFINE_GROUP_RESULT_BUFFER2; //ADC_GROUP0_result ---GPS_ANT_DET
ADC_DEFINE_GROUP_RESULT_BUFFER3; //ADC_GROUP0_result ---SW1
ADC_DEFINE_GROUP_RESULT_BUFFER4; //ADC_GROUP0_result ---SW2
ADC_DEFINE_GROUP_RESULT_BUFFER5; //ADC_GROUP0_result ---TUNER_ANT_DET

/** List of all groups initialized with configured values. */
CONST(Adc_GroupDefType, ADC_VAR) Adc_Group[ADC_NB_GROUP+1] =
{
    ADC_GROUP_LIST_STD_INIT0,
    ADC_GROUP_LIST_STD_INIT1,
    ADC_GROUP_LIST_STD_INIT2,
    ADC_GROUP_LIST_STD_INIT3,
    ADC_GROUP_LIST_STD_INIT4,
    ADC_GROUP_LIST_STD_INIT5,
    ADC_GROUP_DUMMY
};
/* LOCAL OBJECTS -------------------------------------------------------------*/

/*============================================================================*\
 * LOCAL FUNCTION PROTOTYPES
\*============================================================================*/

/*============================================================================*\
 * LOCAL FUNCTION-LIKE-MACROS and INLINE FUNCTIONS
\*============================================================================*/

/*============================================================================*\
 * LOCAL FUNCTIONS
\*============================================================================*/

/*============================================================================*\
 * EXPORTED FUNCTIONS
\*============================================================================*/

/* END OF FILE -------------------------------------------------------------- */

/*===========================================================================*\
 * File Revision History (top to bottom: last revision to first revision)
 *===========================================================================
 * Date          userid    (Description on following lines: SCR #, etc.)
 * -----------  --------   --------------------------------------------------

 * 18-MAR-2011   Wade
 * + Created initial file
 *   - Copied from 10024438_ICP_B78_TCI~10024438_TCI_4_01:project:tci_ik#1
 * + Initial configuration for HVAC and Audio Module
 *
\*===========================================================================*/
