/*============================================================================*\
 * This file was generated by the SCG framework.
 *
 * The configuration parameters were checked statically for correctness
 * by DETECT tool and code generator. DO NOT EDIT THIS FILE MANUALLY!!!
 *
 * \b Application:        DIO \n
 * \b Target:             see Dio_Cfg.h \n
 * \b Compiler:           see Dio_Cfg.h \n
 * \b Module:             Dio_Cfg.c \n
 * \b File-Revision:      1.0.1 \n
 * \b Changeable-by-user: No \n
 * \b Module-Owner:       SSA Team \n
 * \b Last-Modified:      %date_modified% \n
 * \b Classification:     CONFIDENTIAL \n
\*============================================================================*/

/**\file
 * \brief Configuration file for SSA DIO driver.
 * \details This file contains the definitions of configurable objects
 * of the DIO driver for SSA. \n
 * If channel groups are not configured then this file can be empty.
 */

/*============================================================================*\
 *
 * Copyright 2010 Delphi Controls & Security, All Rights Reserved
 * It is not allowed to reproduce or utilize parts of this document in any form
 * or by any means, including photocopying and microfilm, without permission in
 * written by Delphi Electronics & Safety Division.
 *
\*============================================================================*/

/*============================================================================*\
 * PREPROCESSOR DIRECTIVES
\*============================================================================*/

/* INCLUDE DIRECTIVES FOR STANDARD HEADERS -----------------------------------*/

/* INCLUDE DIRECTIVES FOR OTHER HEADERS --------------------------------------*/

#include "Dio.h"

/*
 * Version controls for Dio.h file.
 */
#define DIO_CFG_C_EXPECTED_DIO_H_MAJOR_VERSION (1u)
#define DIO_CFG_C_EXPECTED_DIO_H_MINOR_VERSION (0u)
#define DIO_CFG_C_EXPECTED_DIO_H_PATCH_VERSION (0u)

#define DIO_CFG_C_EXPECTED_AR_MAJOR_VERSION  (2u)
#define DIO_CFG_C_EXPECTED_AR_MINOR_VERSION  (1u)
#define DIO_CFG_C_EXPECTED_AR_PATCH_VERSION  (0u)

#if( (DIO_AR_MAJOR_VERSION != DIO_CFG_C_EXPECTED_AR_MAJOR_VERSION) || \
     (DIO_AR_MINOR_VERSION != DIO_CFG_C_EXPECTED_AR_MINOR_VERSION) || \
     (DIO_AR_PATCH_VERSION != DIO_CFG_C_EXPECTED_AR_PATCH_VERSION) )
#error "AUTOSAR version mismatch between Dio_Cfg.c and Dio.h files."
#endif

#if(   (DIO_SW_MAJOR_VERSION != DIO_CFG_C_EXPECTED_DIO_H_MAJOR_VERSION) || \
       (DIO_SW_MINOR_VERSION != DIO_CFG_C_EXPECTED_DIO_H_MINOR_VERSION))
#error "The version of the Dio_Cfg.c file does not match the version of the Dio.h file"
#endif


/* LOCAL DEFINES FOR CONSTANTS -----------------------------------------------*/

/* LOCAL DEFINE MACROS (#, ##) -----------------------------------------------*/

/*============================================================================*\
 * LOCAL TYPEDEF DECLARATIONS
\*============================================================================*/

/* ENUMS ---------------------------------------------------------------------*/

/* STRUCTS -------------------------------------------------------------------*/

/* UNIONS --------------------------------------------------------------------*/

/* OTHER TYPEDEFS ------------------------------------------------------------*/

/*============================================================================*\
 * OBJECT DEFINITIONS
\*============================================================================*/

/* EXPORTED OBJECTS ----------------------------------------------------------*/

#define DIO_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h"

/* PRQA S 288 ++
   MISRA RULE 3.1 VIOLATION:
   Character (at) is required for doxygen syntax.
 */
/** \defgroup ChannelGroupDefinition
 * \Name ChannelGroup definition.\n
 * \n
 * Note: ChannelGroup names are given only as an example of implementation.
 *
 * @{
 */
CONST(Dio_ChannelGroupType, DIO_CONST) Dio_Group1 = {0, 0, 0x0f};

/* @}*/
/* PRQA S 288 -- */

/**
 * Table holding appropriate data registers and port widths.
 * Index of this table is Dio_PortType.\n
 * \n
 * Note: Register names are given only as an example of implementation.
 */
/*
CONST(Dio_PortInfoType, DIO_CONST) Dio_PortInfoLookup[DIO_NB_PORTS_WITH_CHANNEL_GROUPS] =
{
   {&(P5)}
};
 */
#define DIO_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h"


/* LOCAL OBJECTS -------------------------------------------------------------*/

/*============================================================================*\
 * LOCAL FUNCTION PROTOTYPES
\*============================================================================*/

/*============================================================================*\
 * LOCAL FUNCTION-LIKE-MACROS and INLINE FUNCTIONS
\*============================================================================*/

/*============================================================================*\
 * LOCAL FUNCTIONS
\*============================================================================*/

/*============================================================================*\
 * EXPORTED FUNCTIONS
\*============================================================================*/

/* END OF FILE -------------------------------------------------------------- */

