#ifndef WDG_36_78K0R_FX3CFG_H
#define WDG_36_78K0R_FX3CFG_H
/*============================================================================*\
 * This file was generated by the SCG framework.
 *
 * The configuration parameters were checked statically for correctness
 * by DETECT tool and code generator. DO NOT EDIT THIS FILE MANUALLY!!!
 *
 * \b Application:        WDG \n
 * \b Target:             NEC 78K0R_FX3 \n
 * \b Compiler:           IAR icc78k0r \n
 * \b Module:             Wdg_78K0R_FX3Cfg.h \n
 * \b File-Revision:      1.1.1 \n
 * \b Changeable-by-user: No \n
 * \b Module-Owner:       SSA Team \n
 * \b Last-Modified:      Mon Mar  7 14:22:24 2011 \n
 * \b Classification:     CONFIDENTIAL \n
\*============================================================================*/

/**\file
 * \brief Configuration File for SSA WDG module.
 *
 * \Requirements
 * \reqtrace{SSA-SDD-WDG-13-1}{SSA-REQ-WDG-220-1, SSA-REQ-WDG-378-1}
 */

/*============================================================================*\
 *
 * File generated on 2010/09/27 15:57:30
 * Generated using code generator (EPD) v.1.1.1
 *
\*============================================================================*/

/*============================================================================*\
 *
 * Copyright 2010  Controls & Security, All Rights Reserved
 * It is not allowed to reproduce or utilize parts of this document in any form
 * or by any means, including photocopying and microfilm, without permission in
 * written by  Electronics & Safety Division.
 *
\*============================================================================*/

/*============================================================================*\
 * UNIT TEST
\*============================================================================*/
#define WDG_36_78K0R_FX3UNIT_TEST (STD_OFF)

/*============================================================================*\
 * PREPROCESSOR DIRECTIVES
\*============================================================================*/

/* INCLUDE DIRECTIVES FOR STANDARD HEADERS -----------------------------------*/

/* INCLUDE DIRECTIVES FOR OTHER HEADERS --------------------------------------*/

/* EXPORTED DEFINES FOR CONSTANTS --------------------------------------------*/

/** \brief Component version information API switch.
 *
 * \Requirements
 * \reqtrace{SSA-SDD-WDG-14-1}{SSA-REQ-WDG-325-1, SSA-REQ-WDG-383-1, SSA-REQ-WDG-384-1}
 */
#define WDG_36_78K0R_FX3VERSION_INFO_API (STD_ON)

/** \brief Preprocessor switch for enabling the development error detection.
 *
 * \Requirements
 * \reqtrace{SSA-SDD-WDG-15-1}{SSA-REQ-WDG-230-1, SSA-REQ-WDG-231-1, SSA-REQ-WDG-234-1,
 *                             SSA-REQ-WDG-379-1}
 */
#define WDG_36_78K0R_FX3DEV_ERROR_DETECT (STD_OFF)


/* PRQA S 288 ++
   MISRA RULE 3.1 VIOLATION:
   Character (at) is required for doxygen syntax.
 */
/** \defgroup VersionInfo_Cfg
 * \name Published information:
 * \details
 * - Major, minor and patch version number of AUTOSAR specification on which the
 *   appropriate implementation is based on. \n
 * - Software major, minor and patch version of this module. \n
 * \n
 *   Note: Specific numbers are given only as an example of implementation. \n
 *
 * \Requirements
 * \reqtrace{SSA-SDD-WDG-16-1}{SSA-REQ-WDG-397-1}
 * @{
 */
#define WDG_36_78K0R_FX3CFG_AR_MAJOR_VERSION (2u)
#define WDG_36_78K0R_FX3CFG_AR_MINOR_VERSION (1u)
#define WDG_36_78K0R_FX3CFG_AR_PATCH_VERSION (0u)

#define WDG_36_78K0R_FX3CFG_SW_MAJOR_VERSION (1u)
#define WDG_36_78K0R_FX3CFG_SW_MINOR_VERSION (1u)
#define WDG_36_78K0R_FX3CFG_SW_PATCH_VERSION (0u)
/* @}*/

/** Parameter holds Watchdog Option Byte settings
 * \Requirements
 * \reqtrace{SSA-SDD-WDG-17-1}{SSA-REQ-WDG-381-1, SSA-REQ-WDG-386-1, SSA-REQ-WDG-387-1,
 *                              SSA-REQ-WDG-388-1, SSA-REQ-WDG-389-1, SSA-REQ-WDG-390-1}
 */

/* Format of Watchdog Option Byte */
//#define WDG_36_78K0R_FX3MODE   (0x56u)
#define WDG_36_78K0R_FX3MODE   (0x46u)
/* EXPORTED DEFINE MACROS (#, ##) --------------------------------------------*/

/*============================================================================*\
 * EXPORTED TYPEDEF DECLARATIONS
\*============================================================================*/

/* ENUMS ---------------------------------------------------------------------*/

/* UNIONS --------------------------------------------------------------------*/

/* OTHER TYPEDEFS ------------------------------------------------------------*/

/*============================================================================*\
 * EXPORTED OBJECT DECLARATIONS
\*============================================================================*/

/*============================================================================*\
 * EXPORTED FUNCTIONS PROTOTYPES
\*============================================================================*/

/*============================================================================*\
 * EXPORTED FUNCTION-LIKE-MACROS and INLINE FUNCTIONS
\*============================================================================*/

#endif /* WDG_36_78K0R_FX3CFG_H */

/* END OF FILE -------------------------------------------------------------- */

